CC = gcc
CARGS = -Wall -g

all: p01 p02 p03 p04 p05 p06 p07 p08 p09 p10 bonus

p01: p01.c
	$(CC) $(CARGS) -o p01 p01.c

p02: p02.c
	$(CC) $(CARGS) -o p02 p02.c -lm

p03: p03.c
	$(CC) $(CARGS) -o p03 p03.c

p04: p04.c
	$(CC) $(CARGS) -o p04 p04.c

p05: p05.c
	$(CC) $(CARGS) -o p05 p05.c

p06: p06.c
	$(CC) $(CARGS) -o p06 p06.c

p07: p07.c
	$(CC) $(CARGS) -o p07 p07.c

p08: p08.c
	$(CC) $(CARGS) -o p08 p08.c

p09: p09.c
	$(CC) $(CARGS) -o p09 p09.c

p10: p10.c
	$(CC) $(CARGS) -o p10 p10.c

bonus: bonus.c
	$(CC) $(CARGS) -o bonus bonus.c

clean: 
	rm -f p{01..10} bonus
